//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.VisualStudio.MDebugger {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.VisualStudio.MDebugger.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apples 的本地化字符串。
        /// </summary>
        internal static string Apples {
            get {
                return ResourceManager.GetString("Apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bananas 的本地化字符串。
        /// </summary>
        internal static string Bananas {
            get {
                return ResourceManager.GetString("Bananas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bears 的本地化字符串。
        /// </summary>
        internal static string Bears {
            get {
                return ResourceManager.GetString("Bears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both in and out parameters should not be specified 的本地化字符串。
        /// </summary>
        internal static string BothInOutParamsIllegal {
            get {
                return ResourceManager.GetString("BothInOutParamsIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty string is not accepted 的本地化字符串。
        /// </summary>
        internal static string EmptyStringIllegal {
            get {
                return ResourceManager.GetString("EmptyStringIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EventArgs are required 的本地化字符串。
        /// </summary>
        internal static string EventArgsRequired {
            get {
                return ResourceManager.GetString("EventArgsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both in and out parameters can not be NULL 的本地化字符串。
        /// </summary>
        internal static string InOutParamCantBeNULL {
            get {
                return ResourceManager.GetString("InOutParamCantBeNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In parameter may not be specified 的本地化字符串。
        /// </summary>
        internal static string InParamIllegal {
            get {
                return ResourceManager.GetString("InParamIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value should be between 0 and {0} 的本地化字符串。
        /// </summary>
        internal static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lions 的本地化字符串。
        /// </summary>
        internal static string Lions {
            get {
                return ResourceManager.GetString("Lions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My DropDown Combo 的本地化字符串。
        /// </summary>
        internal static string MyDropDownCombo {
            get {
                return ResourceManager.GetString("MyDropDownCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Dynamic Combo 的本地化字符串。
        /// </summary>
        internal static string MyDynamicCombo {
            get {
                return ResourceManager.GetString("MyDynamicCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Index Combo 的本地化字符串。
        /// </summary>
        internal static string MyIndexCombo {
            get {
                return ResourceManager.GetString("MyIndexCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oranges 的本地化字符串。
        /// </summary>
        internal static string Oranges {
            get {
                return ResourceManager.GetString("Oranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out parameter can not be NULL 的本地化字符串。
        /// </summary>
        internal static string OutParamRequired {
            get {
                return ResourceManager.GetString("OutParamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter must be either index or valid string in list 的本地化字符串。
        /// </summary>
        internal static string ParamMustBeValidIndexOrStringInList {
            get {
                return ResourceManager.GetString("ParamMustBeValidIndexOrStringInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter must be valid string in list 的本地化字符串。
        /// </summary>
        internal static string ParamNotValidStringInList {
            get {
                return ResourceManager.GetString("ParamNotValidStringInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pears 的本地化字符串。
        /// </summary>
        internal static string Pears {
            get {
                return ResourceManager.GetString("Pears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tigers 的本地化字符串。
        /// </summary>
        internal static string Tigers {
            get {
                return ResourceManager.GetString("Tigers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom to Fit 的本地化字符串。
        /// </summary>
        internal static string Zoom_to_Fit {
            get {
                return ResourceManager.GetString("Zoom_to_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom factor must be &gt; 0 的本地化字符串。
        /// </summary>
        internal static string ZoomMustBeGTZero {
            get {
                return ResourceManager.GetString("ZoomMustBeGTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZoomToFit 的本地化字符串。
        /// </summary>
        internal static string ZoomToFit {
            get {
                return ResourceManager.GetString("ZoomToFit", resourceCulture);
            }
        }
    }
}
